services:
  dev:
    image: vs-knex-schema-inspector
    build:
      context: ../
      dockerfile: docker/dev/Dockerfile
      args:
        - IDIR=knex-schema-inspector
    volumes:
      - ../:/ws/knex-schema-inspector:cached
      - lib-modules:/ws/knex-schema-inspector/node_modules

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file: ../.env
    environment:
      # not in .env because .env can be used in prod too
      FORCE_UID: 1001
      FORCE_GID: 1001
    deploy:
      resources:
        limits:
          cpus: '2'
volumes:
  lib-modules:

networks:
  default:
    name: docker_default
    external: true
